var funcion= require('./about_asserts.js')
funcion()
funcion= require('./about_operators.js')
funcion()
funcion= require('./about_equality.js')
funcion()
funcion= require('./about_truthyness.js')
funcion()
funcion= require('./about_assignment.js')
funcion()
funcion= require('./about_control_structures.js')
funcion()
funcion= require('./about_strings.js')
funcion()
funcion= require('./about_numbers.js')
funcion()
funcion= require('./about_objects.js')
funcion()
funcion= require('./about_arrays.js')
funcion()
funcion= require('./about_reflection.js')
funcion()
funcion= require('./about_prototype_chain.js')
funcion()
funcion= require('./about_prototypal_inheritance.js')
funcion()
funcion= require('./about_functions_and_closure.js')
funcion()
funcion= require('./about_this.js')
funcion()
funcion= require('./about_scope.js')
funcion()
funcion= require('./about_regular_expressions.js')
funcion()